# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(10, 0, 1121, 661))
        self.frame1.setStyleSheet("QFrame{\n"
"    background-color:rgb(220, 220, 220);\n"
"    border:0px solid red;\n"
"    border-radius:30px\n"
"}")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.frame2 = QtWidgets.QFrame(self.frame1)
        self.frame2.setGeometry(QtCore.QRect(280, 0, 841, 661))
        self.frame2.setStyleSheet("QFrame{\n"
"    background-color:rgb(220, 220, 220);\n"
"    border:0px solid red;\n"
"    border-radius:30px\n"
"}")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.frame3 = QtWidgets.QFrame(self.frame2)
        self.frame3.setGeometry(QtCore.QRect(0, 0, 331, 321))
        self.frame3.setStyleSheet("background-color:rgb(255, 165, 142);")
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.tomato_time = QtWidgets.QLabel(self.frame3)
        self.tomato_time.setGeometry(QtCore.QRect(68, 60, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.tomato_time.setFont(font)
        self.tomato_time.setStyleSheet("")
        self.tomato_time.setAlignment(QtCore.Qt.AlignCenter)
        self.tomato_time.setObjectName("tomato_time")
        self.tomato_start = QtWidgets.QPushButton(self.frame3)
        self.tomato_start.setGeometry(QtCore.QRect(265, 160, 60, 40))
        self.tomato_start.setStyleSheet("border: none;\n"
"image:url(D:/酪梨資料夾/大學作業/專題/pyqt/demo/img/start.png);")
        self.tomato_start.setText("")
        self.tomato_start.setIconSize(QtCore.QSize(30, 30))
        self.tomato_start.setObjectName("tomato_start")
        self.tomato_change = QtWidgets.QPushButton(self.frame3)
        self.tomato_change.setGeometry(QtCore.QRect(10, 20, 60, 40))
        self.tomato_change.setStyleSheet("border: none;\n"
"image:url(D:/酪梨資料夾/大學作業/專題/pyqt/demo/img/setting.png);")
        self.tomato_change.setText("")
        self.tomato_change.setObjectName("tomato_change")
        self.tomato_skip = QtWidgets.QPushButton(self.frame3)
        self.tomato_skip.setGeometry(QtCore.QRect(265, 20, 60, 40))
        self.tomato_skip.setStyleSheet("border: none;\n"
"image:url(D:/酪梨資料夾/大學作業/專題/pyqt/demo/img/skip.png);")
        self.tomato_skip.setText("")
        self.tomato_skip.setIconSize(QtCore.QSize(30, 30))
        self.tomato_skip.setObjectName("tomato_skip")
        self.frame3_1 = QtWidgets.QFrame(self.frame3)
        self.frame3_1.setGeometry(QtCore.QRect(20, 210, 291, 91))
        self.frame3_1.setStyleSheet("background-color:rgb(220, 220, 220);")
        self.frame3_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_1.setObjectName("frame3_1")
        self.tomato_mode = QtWidgets.QLabel(self.frame3_1)
        self.tomato_mode.setGeometry(QtCore.QRect(20, 0, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.tomato_mode.setFont(font)
        self.tomato_mode.setStyleSheet("")
        self.tomato_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.tomato_mode.setObjectName("tomato_mode")
        self.frame4 = QtWidgets.QFrame(self.frame2)
        self.frame4.setGeometry(QtCore.QRect(340, 0, 501, 321))
        self.frame4.setStyleSheet("background-color:rgb(153, 153, 153);")
        self.frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame4.setObjectName("frame4")
        self.face_tracking = QtWidgets.QLabel(self.frame4)
        self.face_tracking.setGeometry(QtCore.QRect(20, 20, 461, 281))
        self.face_tracking.setObjectName("face_tracking")
        self.frame5 = QtWidgets.QFrame(self.frame2)
        self.frame5.setGeometry(QtCore.QRect(0, 330, 841, 331))
        self.frame5.setStyleSheet("background-color:rgb(149, 206, 217);")
        self.frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setObjectName("frame5")
        self.label_3 = QtWidgets.QLabel(self.frame5)
        self.label_3.setGeometry(QtCore.QRect(340, 120, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.user = QtWidgets.QFrame(self.frame1)
        self.user.setGeometry(QtCore.QRect(20, 60, 231, 141))
        self.user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user.setObjectName("user")
        self.usericon = QtWidgets.QFrame(self.user)
        self.usericon.setGeometry(QtCore.QRect(10, 10, 216, 64))
        self.usericon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.usericon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usericon.setObjectName("usericon")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.usericon)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.user_icon = QtWidgets.QWidget(self.usericon)
        self.user_icon.setMinimumSize(QtCore.QSize(64, 64))
        self.user_icon.setMaximumSize(QtCore.QSize(64, 64))
        self.user_icon.setStyleSheet("image:url(D:/酪梨資料夾/大學作業/專題/pyqt/demo/img/user.png);\n"
"border-radius:32px")
        self.user_icon.setObjectName("user_icon")
        self.horizontalLayout_15.addWidget(self.user_icon)
        self.username = QtWidgets.QLabel(self.user)
        self.username.setGeometry(QtCore.QRect(10, 74, 216, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.fuctionlist = QtWidgets.QListWidget(self.frame1)
        self.fuctionlist.setGeometry(QtCore.QRect(20, 240, 238, 252))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fuctionlist.setFont(font)
        self.fuctionlist.setStyleSheet("QListView {\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"    color: rgb(67, 67, 67);\n"
"    padding:10px;\n"
"    padding-left:5px;\n"
"    margin-bottom:8px;\n"
"}\n"
"QListView::item:hover {\n"
"border-radius:8px;\n"
"    background-color: rgb(240, 240, 240)\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.fuctionlist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fuctionlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fuctionlist.setObjectName("fuctionlist")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.fuctionlist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/exercise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.fuctionlist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/news.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.fuctionlist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/setting2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.fuctionlist.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.fuctionlist.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tomato_time.setText(_translate("MainWindow", "25:00"))
        self.tomato_mode.setText(_translate("MainWindow", "WORK"))
        self.face_tracking.setText(_translate("MainWindow", "opencv"))
        self.label_3.setText(_translate("MainWindow", "待辦清單"))
        self.username.setText(_translate("MainWindow", "user"))
        __sortingEnabled = self.fuctionlist.isSortingEnabled()
        self.fuctionlist.setSortingEnabled(False)
        item = self.fuctionlist.item(0)
        item.setText(_translate("MainWindow", "首頁"))
        item = self.fuctionlist.item(1)
        item.setText(_translate("MainWindow", "伸展操"))
        item = self.fuctionlist.item(2)
        item.setText(_translate("MainWindow", "新聞"))
        item = self.fuctionlist.item(3)
        item.setText(_translate("MainWindow", "設定"))
        self.fuctionlist.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
